apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/att-admin-authen
  newTag: 921aa454


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: att-admin-authen-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: att-admin-authen-secret-env
