# don't forget to update config.model
environment: sit

app:
  name: authen

server:
  port: 8080
  timeout: 30s

log:
  environment: production
  level: info
  format: json


# kafka:
#   address: 
#     - kafka.poc.internal:9092
#   topic: example-topic
#   consume-group: att-user-consumer-group


postgres:
  host: 172.28.240.42
  port: 5432
  db-name: att-db
  # postgres:
  # host: localhost
  # port: 5432
  # db-name: example-db


redis:
  address: 172.28.241.3:6379
  database: 0

# product-list-key: ATT_USER_LIST

email-info:
  email: testdevatt@gmail.com
  subject: "OTP verification code received"

