apiVersion: apps/v1
kind: Deployment
metadata:
  name: att-admin-authen
  labels:
    app.kubernetes.io/name: att-admin-authen
    app.kubernetes.io/instance: att-admin-authen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: att-admin-authen
      app.kubernetes.io/instance: att-admin-authen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: att-admin-authen
        app.kubernetes.io/instance: att-admin-authen
    spec:
      containers:
        - name: att-admin-authen
          image: asia.gcr.io/poc-innovation-iot/att-admin-authen:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: att-admin-authen-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: att-admin-authen-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 64m
              memory: 512Mi
            requests:
              cpu: 32m
              memory: 256Mi
      volumes:
        - name: att-admin-authen-secret-file
          secret:
            secretName: att-admin-authen-secret-file
        - name: att-admin-authen-configmap-file
          configMap:
            name: att-admin-authen-configmap-file

        